// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Constantine",
            "url": "https://github.com/Constantine-Ka/corsmiddleware"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "post": {
                "parameters": [
                    {
                        "type": "string",
                        "description": "http-метод, с которым нужно отправить запрос",
                        "name": "_method",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "URL по которому нужно выполнить запрос",
                        "name": "_url",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Заголовки, которые нужно передать",
                        "name": "_headers",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Тело запроса, которые нужно передать в raw",
                        "name": "_json",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Любые поля и значения в формате formdata",
                        "name": "прочее",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response from the target URL",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request.  Check the error message for details.",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "CORS Midlleware",
	Description:      "Сервис-посредник, для работы с rest API, с защитой КОРС",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
